from utils.replace_functions import replace_ege, replace_cge
from utils.import_geothermal import import_geothermal_database
from ege_klausen import parameters as parameters_ege
from cge_klausen import parameters as parameters_cge
from cge_model import GeothermalConventionalModel
from ege_model import GeothermalEnhancedModel

import_geothermal_database()

replace_cge(parameters_cge,GeothermalConventionalModel)
replace_ege(parameters_ege,GeothermalEnhancedModel)
